#!/bin/bash
 
### BEGIN INIT INFO
# Provides:          daemon_200412335
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Daemon con fines Educativos - 200412335
### END INIT INFO
 
# Fuentes de los LSB helpers
. /lib/lsb/init-functions
 
# Nombre del proceso (solo para mostrar)
NAME=daemon_200412335
 
# En donde se encuentra el ejecutable del daemon
DAEMON="/home/juanmarcos/daemon_200412335/daemon_200412335.py"
DAEMON_ARGS="/home/juanmarcos/daemon_200412335/daemon_200412335.ini"
 
# El usuario: grupo bajo el cual el daemon correra.
RUN_AS_USER=juanmarcos
 
# pid del archivo del daemon.
PIDFILE=/var/run/daemon_200412335.pid
 
# Si no se encuentra el daemon, entonces salir.
if ! [ -x ${DAEMON} ] ; then
    log_failure_msg "No se puede encontrar ejecutable en ${DAEMON}"
    exit 1
fi
 
case $1 in
    start)
        # Verificar si el archivo del pid existe.
        if [ -e ${PIDFILE} ]; then
            # Verificar el estatus actual del proceso.
            status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME} && status="0" || status="$?"
            # Si el estatus es exitoso, no es necesario volverlo a iniciar.
            [ ${status} = "0" ] && exit 0
        fi
        # Iniciar daemon.
        log_daemon_msg "Iniciando ${NAME}" 
        # Iniciar el daemon con la ayuda de start-stop-daemon
        start-stop-daemon -S --quiet --oknodo --pidfile ${PIDFILE} --make-pidfile --background \
            --chuid ${RUN_AS_USER} --startas ${DAEMON} -- ${DAEMON_ARGS}
        if [ "$?" == "0" ]; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    stop)
        if [ -e ${PIDFILE} ]; then
            status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME} && status="0" || status="$?"
            if [ "$status" = "0" ]; then
                log_daemon_msg "Deteniedo ${NAME}" 
                start-stop-daemon -K --signal TERM --quiet --oknodo --pidfile ${PIDFILE}
                if [ "$?" == "0" ]; then
                    log_end_msg 0
                    rm -rf ${PIDFILE}
                else
                    log_end_msg 1
                fi
            fi
        else
            log_daemon_msg "${NAME} no esta Corriendo"
            log_end_msg 0
        fi
        ;;
    restart)
        $0 stop && sleep 3 && $0 start
        ;;
    status)
        # Verificar el estatus del proceso.
        if [ -e ${PIDFILE} ]; then
            status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME} && exit 0 || exit $?
        else
            log_daemon_msg "${NAME} No esta Corriendo (no hay archivo pid)"
            log_end_msg 0
        fi
        ;;
    reload)
        if [ -e ${PIDFILE} ]; then
            log_daemon_msg "Recargando ${NAME}" 
            start-stop-daemon -K --quiet --signal HUP --pidfile ${PIDFILE}
            if [ "$?" == "0" ]; then
                log_end_msg 0
            else
                log_end_msg 1
            fi
        else
            log_failure_msg "No se puede encontrar archivo pid en ${PIDFILE}"
        fi
        ;;
    *)
        # Argumento Invalido, pintar este mensaje.
        echo "Modo de uso: $0 {start|stop|restart|reload|status}"
        exit 2
        ;;
esac
